apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: qic0z2ch6-go
  janus-idp.io/tekton: qic0z2ch6-go
  backstage.io/kubernetes-id: qic0z2ch6-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: qic0z2ch6-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
